---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gateway-cert
  namespace: kube-system
spec:
  secretName: gateway-cert
  commonName: '*.svc.pt.soeren.cloud'
  dnsNames:
    - '*.svc.pt.soeren.cloud'
  issuerRef:
    name: letsencrypt-dns-prod
    kind: ClusterIssuer
    group: cert-manager.io
